### ISSUE TITLE
wonderful but rotates the video somehow?

### ISSUE THREAD

**Issue by randomgambit** [Sxela/ArcaneGAN#11]
wonderful work! really a nice piece of code. My only worry is that the code rotates my videos. Is this expected? how can I fix that?

Thanks!

**Comment by Sxela** [comment]
I suppose this may have something to do with EXIF data. Your video is rotated, but EXIF data lets your device show it correctly. After processing the EXIF is stripped, and your video is displayed as-is (rotated).

**Comment by randomgambit** [comment]
very interesting point. thanks! can we re rotate it programmatically using python?

**Comment by Sxela** [comment]
Something like this may help 
https://stackoverflow.com/questions/10221762/how-to-edit-or-add-video-metadata-of-rotation-in-mp4
On the other hand, I don't know exactly which pipeline you are using, maybe it rotates the video based on exif.
