### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Zzip7** [Sxela/ArcaneGAN#12]
Добрый вечер.В ArcaneGAN на colab for videos,выдаёт ошибку:

RuntimeError: CUDA out of memory. Tried to allocate 2.80 GiB (GPU 0; 11.17 GiB total capacity; 5.74 GiB already allocated; 2.21 GiB free; 8.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Помогите пожалуйста!

**Comment by Sxela** [comment]
Такое часто там бывает. Перезапустил.

**Comment by Zzip7** [comment]
Спасибо за оперативность!!!  Удачи вам!

**Comment by Zzip7** [comment]
Добрый вечер.Извините,это опять я.Снова эта ошибка появляется.Можно ли,самому эту ошибку решать?Или исправлять можете только вы?Обьясните пожалуйста подробно.
