### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by Zzip7** [Sxela/ArcaneGAN#13]
Добрый вечер.Извините,это опять я.Снова эта ошибка появляется.Можно ли,самому эту ошибку решать?Или исправлять можете только вы?Обьясните пожалуйста подробно.

**Comment by Sxela** [comment]
Привет! Проще запустить в колабе - 
https://colab.research.google.com/drive/1ohKCiOwZrhM3pza4L93AHAfMkIkJ5YQF
