### ISSUE TITLE
How to prevent eyes occur in nose?

### ISSUE THREAD

**Issue by Folkfive** [Sxela/ArcaneGAN#19]
Hello, I try your model and it's amazing, but I find in some pictures if the nose is too big, there will be eyes in the nose. I try to lower the 'target_face' and it can work. But the details like the light of the eyes and background will also lose when I lower the 'target_face'. So I wonder is there a way to prevent the eyes occurs in the nose and keep the details in the meantime?
![image](https://user-images.githubusercontent.com/22257912/162709349-aa05a392-75a4-4a26-9549-9c6bb0841692.png)

**Comment by Sxela** [comment]
Hi! The model was trained on 256-400px faces, so it's best to keep faces inside this size range. You canprocess faces separately, upscale them with realesrgan-anime, and paste them back into background, for example.
