### ISSUE TITLE
How to convert the FastAI model to Pytorch JIT

### ISSUE THREAD

**Issue by ramtiin** [Sxela/ArcaneGAN#23]
Hi,

I trained a model with unet_learner but I can't convert it to jit. 

I run the following code:
`torch.jit.save(torch.jit.script(learn.model), 'jit.pt')`

Here is the error:

`UnsupportedNodeError: GeneratorExp aren't supported:
  File "/usr/local/lib/python3.7/dist-packages/fastai/callbacks/hooks.py", line 21
        "Applies `hook_func` to `module`, `input`, `output`."
        if self.detach:
            input  = (o.detach() for o in input ) if is_listy(input ) else input.detach()
                      ~ <--- HERE
            output = (o.detach() for o in output) if is_listy(output) else output.detach()
        self.stored = self.hook_func(module, input, output)`

May I know how you convert it to a jit model?
Thanks

**Comment by Sxela** [comment]
Try using torch.jit.trace with (1,3,258,258) trace input size

**Comment by ramtiin** [comment]
Thanks, it worked!
