### ISSUE TITLE
face alignment

### ISSUE THREAD

**Issue by rainsoulsrx** [Sxela/ArcaneGAN#5]
Hi, do you make face alignment before you give it to your Unet model?

**Comment by Sxela** [comment]
I'm not doing that in my inference notebook, as the model was trained with rotation augmentations. 
You can do it, it improves the result a bit, especially for extremely rotated faces.

**Comment by rainsoulsrx** [comment]
> I'm not doing that in my inference notebook, as the model was trained with rotation augmentations. You can do it, it improves the result a bit, especially for extremely rotated faces.

Besides rotation augmentations, did you use translation augmentations? Because in your video, the face is not in the middle( just like following pic)  but the training data generated by stylegan is face middle:
![image](https://user-images.githubusercontent.com/24955512/145939156-1162757d-238a-457b-b091-bb4e871a5b75.png)

**Comment by Sxela** [comment]
I've used random zoom\crop, rotation, translation, warp, lighting. Pretty much everything :D

**Comment by rainsoulsrx** [comment]
> I've used random zoom\crop, rotation, translation, warp, lighting. Pretty much everything :D

Got it, thanks a lot!~~
