### ISSUE TITLE
How do you change the style of the whole image

### ISSUE THREAD

**Issue by zhanglonghao1992** [Sxela/ArcaneGAN#6]
Nice work!
My only confusion is how you change the style of the whole image instead of just the face. Usually, StyleGAN generates aligned face images by fine-tuning the FFHQ checkpoint. How does the pix2pix model trained with these face image pairs work with the full image or frame.

**Comment by Gutianpei** [comment]
Hello,

I have the same question. My understanding is you first stylize the face images by pixel2pixel with data generated by finetuned StyleGAN, then you use some filter (like AnimeGAN?) to stylize the entire image and put the face back?

**Comment by Sxela** [comment]
I use heavy augmentation: 
https://github.com/Sxela/ArcaneGAN/issues/5#event-5761991950

**Comment by zhanglonghao1992** [comment]
@Sxela Many thanks! I will try it.
