### ISSUE TITLE
Where can we download the corresponding model for v0.4?

### ISSUE THREAD

**Issue by chinsyo** [Sxela/ArcaneGAN#9]
I noticed that you updated the model, but did not find the new version in the code repository or release.

**Comment by knoel99** [comment]
It's accessible for patreons right now, and will be public after Christmas, as stated in this tweet:https://twitter.com/devdef/status/1473668908372709386?s=20

**Comment by Sxela** [comment]
That's right. It will be released here on December, 25.

**Comment by Sxela** [comment]
https://github.com/Sxela/ArcaneGAN/releases/tag/v0.4
As promised :D 
Merry Christmas!

**Comment by knoel99** [comment]
Thanks Alex, but I don't find in the Readme the collab link with version 0.4

**Comment by Sxela** [comment]
It's been in the repo's readme, but I've added it to release notes as well, thanks for noticing.

**Comment by chinsyo** [comment]
Thanks Alex.

**Comment by seawater668** [comment]
> https://github.com/Sxela/ArcaneGAN/releases/tag/v0.4 正像承诺的那样：D 圣诞快乐！

how to open jit file
